CREATE DATABASE IF NOT EXISTS hospitales;

use hospitales;

CREATE TABLE ENFERMO (
  INSCRIPCION INTEGER(5) UNSIGNED  NOT NULL  ,
  APELLIDO VARCHAR(15)  NULL  ,
  DIRECCION VARCHAR(20)  NULL  ,
  FECHA_NAC DATE  NULL  ,
  S VARCHAR(1)  NULL  ,
  NSS INTEGER(9) UNSIGNED  NULL    ,
PRIMARY KEY(INSCRIPCION));



CREATE TABLE HOSPITAL (
  HOSPITAL_COD INTEGER(2) UNSIGNED  NOT NULL  ,
  NOMBRE VARCHAR(10)  NULL  ,
  DIRECCION VARCHAR(20)  NULL  ,
  TELEFONO VARCHAR(8)  NULL  ,
  NUM_CAMA INTEGER(3) UNSIGNED  NULL    ,
PRIMARY KEY(HOSPITAL_COD));



CREATE TABLE DPT2 (
  DPT_NO INTEGER(2) UNSIGNED  NOT NULL  ,
  NOMBRE VARCHAR(12)  NULL  ,
  LOC VARCHAR(12)  NULL    ,
PRIMARY KEY(DPT_NO));



CREATE TABLE SALA (
  SALA_COD INTEGER(2) UNSIGNED  NOT NULL  ,
  HOSPITAL_COD INTEGER(2) UNSIGNED  NOT NULL  ,
  NOMBRE VARCHAR(20)  NULL  ,
  NUM_CAMA INTEGER(3) UNSIGNED  NULL    ,
PRIMARY KEY(SALA_COD)  ,
INDEX SALA_FKIndex1(HOSPITAL_COD),
  FOREIGN KEY(HOSPITAL_COD)
    REFERENCES HOSPITAL(HOSPITAL_COD)
      ON DELETE RESTRICT
      ON UPDATE CASCADE);



CREATE TABLE DOCTOR (
  DOCTOR_NO INTEGER(3) UNSIGNED  NOT NULL  ,
  HOSPITAL_COD INTEGER(2) UNSIGNED  NOT NULL  ,
  APELLIDO VARCHAR(13)  NULL  ,
  ESPECIALIDAD VARCHAR(16)  NULL    ,
PRIMARY KEY(DOCTOR_NO)  ,
INDEX DOCTOR_FKIndex1(HOSPITAL_COD),
  FOREIGN KEY(HOSPITAL_COD)
    REFERENCES HOSPITAL(HOSPITAL_COD)
      ON DELETE RESTRICT
      ON UPDATE CASCADE);



CREATE TABLE EMP (
  EMP_NO INTEGER(4) UNSIGNED  NOT NULL  ,
  DPT2_DPT_NO INTEGER(2) UNSIGNED  NOT NULL  ,
  APELLIDO VARCHAR(10)  NULL  ,
  OFICIO VARCHAR(10)  NULL  ,
  DIR INTEGER(4) UNSIGNED  NULL  ,
  FECHA_ALTA DATE  NULL  ,
  SALARIO INTEGER(10) UNSIGNED  NULL  ,
  COMISION INTEGER(10) UNSIGNED  NULL    ,
PRIMARY KEY(EMP_NO)  ,
INDEX EMP_FKIndex1(DPT2_DPT_NO),
  FOREIGN KEY(DPT2_DPT_NO)
    REFERENCES DPT2(DPT_NO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE);



CREATE TABLE PLANTILLA (
  HOSPITAL_COD INTEGER(2) UNSIGNED  NOT NULL  ,
  EMP_NO INTEGER(4) UNSIGNED  NOT NULL  ,
  SALA_COD INTEGER(2) UNSIGNED  NOT NULL  ,
  APELLIDO VARCHAR(15)  NULL  ,
  FUNCION VARCHAR(10)  NULL  ,
  TURNO VARCHAR(1)  NULL  ,
  SALARIO INTEGER(10) UNSIGNED  NULL    ,
PRIMARY KEY(HOSPITAL_COD)  ,
INDEX PLANTILLA_FKIndex1(HOSPITAL_COD)  ,
INDEX PLANTILLA_FKIndex2(SALA_COD)  ,
INDEX PLANTILLA_FKIndex3(EMP_NO),
  FOREIGN KEY(HOSPITAL_COD)
    REFERENCES HOSPITAL(HOSPITAL_COD)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  FOREIGN KEY(SALA_COD)
    REFERENCES SALA(SALA_COD)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  FOREIGN KEY(EMP_NO)
    REFERENCES EMP(EMP_NO)
      ON DELETE RESTRICT
      ON UPDATE CASCADE);



CREATE TABLE OCUPACION (
  ENFERMO_INSCRIPCION INTEGER(5) UNSIGNED  NOT NULL  ,
  SALA_COD INTEGER(2) UNSIGNED  NOT NULL  ,
  HOSPITAL_COD INTEGER(2) UNSIGNED  NOT NULL  ,
  CAMA INTEGER(4) UNSIGNED  NULL    ,
PRIMARY KEY(ENFERMO_INSCRIPCION)  ,
INDEX OCUPACION_FKIndex1(HOSPITAL_COD)  ,
INDEX OCUPACION_FKIndex2(SALA_COD)  ,
INDEX OCUPACION_FKIndex3(ENFERMO_INSCRIPCION),
  FOREIGN KEY(HOSPITAL_COD)
    REFERENCES HOSPITAL(HOSPITAL_COD)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  FOREIGN KEY(SALA_COD)
    REFERENCES SALA(SALA_COD)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  FOREIGN KEY(ENFERMO_INSCRIPCION)
    REFERENCES ENFERMO(INSCRIPCION)
      ON DELETE RESTRICT
      ON UPDATE CASCADE);




